version: "3.3"

services:
  # https://hub.docker.com/r/spine3/firebase-emulator
  firestore-emulators:
    image: spine3/firebase-emulator:latest
    ports:
      - 8080:8080 # Firestore emulator
      - 4000:4000 # UI emulator
      - 8085:8085 # Pubsub emulator

    environment:
      GCP_PROJECT: "local-gcloud-project"

  elastic-search:
    image: elasticsearch:8.1.3
    environment:
      bootstrap.memory_lock: true
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: SomeTestPass
      xpack.security.enabled: true
  
  neo4j-community:
    image: neo4j:3.5.32-community
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_maxSize: 4G
      NEO4J_dbms_memory_heap_initialSize: 512M
      NEO4J_AUTH: neo4j/SomeTestPass
